Fix a build error undefined reference to `mbox_send_message'
refer to commit a86473962139a("arm: arch: enable rpmsg for imx amp soc")
imx6sx soc has seleted HAVE_IMX_RPMSG, so enable MAILBOX config

Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>