nxp-imx6: Fix a build error undefined reference to `dw_pcie_read_dbi'
refer to commit 4e9a723c0902("pci: imx: add the imx8qxp ep support")
modify PCI_IMX6 to PCI_IMX6_HOST

Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>