powerpc: Disable attribute-alias warnings from gcc8
Source: yocto-kernel-cache
MR: 00000
Type: Integration
Disposition: Merged from yocto-kernel-cache
ChangeID: c4902ee86c8c050c3b307d471bb66b8175b0ffa2
Description:

1/2 [
Author: Khem Raj
Email: raj.khem@gmail.com
Subject: powerpc: Disable attribute-alias warnings from gcc8
Date: Fri, 4 May 2018 09:46:42 -0700

Fixes
alias between functions of incompatible types warnings
which are new with gcc8

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>
]

2/2 [
Author: Khem Raj
Email: raj.khem@gmail.com
Subject: powerpc/ptrace: Disable array-bounds warning with gcc8
Date: Fri, 4 May 2018 09:50:05 -0700

This masks the new gcc8 warning
include/linux/regset.h:270:4: error: 'memcpy' offset [-527, -529] is out of the bounds [0, 16] of object 'vrsave' with type 'union <anonymous>'

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>
]

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>
Signed-off-by: Jeremy Puhlman <jpuhlman@mvista.com>