linux-yocto/rt: enable kprobes by default
Traditionally kprobes and -rt haven't mixed well, but recent -rt
kernels support kprobes without issues.

lttng now requires kprobes to be enabled, or the following error
is thrown:

|
build/tmp/work/qemux86_64-poky-linux/lttng-modules/2.12.2-r0/lttng-modules-2.12.2/wrapper/kallsyms.c:20:3:
error: #error "LTTng-modules requires CONFIG_KPROBES on kernels >= 5.7.0"
|    20 | # error "LTTng-modules requires CONFIG_KPROBES on kernels >= 5.7.0"
|       |   ^~~~~
| make[3]: ***
[build/tmp/work-shared/qemux86-64/kernel-source/scripts/Makefile.build:280:
build/tmp/work/qemux86_64-poky-linux/lttng-modules/2.12.2-r0/lttng-modules-2.12.2/wrapper/kallsyms.o]
Error 1

By including the kprobes fragment into the -rt kernel by default, we
fix the issue.

Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>