yaffs2: switch from readlink_copy() to vfs_readlink()
1/1 [
    Author: Mikko Rapeli
    Email: mikko.rapeli@linaro.org
    Subject: yaffs2: switch from readlink_copy() to vfs_readlink()
    Date: Fri, 14 Mar 2025 10:33:42 +0200

    To compile also as module. Fixes:

    ERROR: modpost: "readlink_copy" [fs/yaffs2/yaffs.ko] undefined!

    Signed-off-by: Mikko Rapeli <mikko.rapeli@linaro.org>
    Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>
]

Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>