marvell-cn106xx: remove PSTORE related kernel configs
Now, CONFIG_PSTORE and CONFIG_MMC_PSTORE_BACKEND are enabled
for marvell-cn106xx platform. But in linux-yocto v5.10.55, it involved an
upstream commit d07f3b081ee6("mark pstore-blk as broken") that causes
build error as below:
/usr/src/kernel/fs/pstore/blk.c:158: undefined reference to `register_pstore_zone'
/usr/src/kernel/fs/pstore/blk.c:190: undefined reference to `unregister_pstore_zone'
According to the comment of the upstream commit, it is need to disable
PSTORE feature on marvell-cn106xx platform. So, remove PSTORE related
kernel configs from kernel cache.

Signed-off-by: Meng Li <Meng.Li@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>