config: set CONFIG_LIBCRC32C=y
Since commit d5178578bcd461cc79118c7a139882350fe505aa

Author: Johannes Thumshirn <jthumshirn@suse.de>
Date:   Mon Jun 3 16:58:57 2019 +0200

    btrfs: directly call into crypto framework for checksumming

We now have a dependency on crc32 in crypto, and it must be built
into the kernel to avoid:

    | x86_64-poky-linux-ld.bfd: fs/btrfs/super.o: in function
    `btrfs_mount_root':
    | super.c:(.text+0xb9b6): undefined reference to `crc32c_impl'
    | x86_64-poky-linux-ld.bfd: fs/btrfs/super.o: in function
    `init_btrfs_fs':
    | super.c:(.init.text+0x362b): undefined reference to `crc32c_impl'
    | x86_64-poky-linux-ld.bfd: fs/btrfs/extent-tree.o: in function
    `hash_extent_data_ref':
    | extent-tree.c:(.text+0xdfa): undefined reference to `crc32c'
    | x86_64-poky-linux-ld.bfd: extent-tree.c:(.text+0xe13): undefined
    reference to `crc32c'
    | x86_64-poky-linux-ld.bfd: extent-tree.c:(.text+0xe27): undefined
    reference to `crc32c'
    | x86_64-poky-linux-ld.bfd: fs/btrfs/dir-item.o: in function
    `btrfs_insert_xattr_item':
    | dir-item.c:(.text+0x286): undefined reference to `crc32c'

So we set our defaults to cover the btrfs build cases without error.

Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>